{% set name = "earthformer" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/earthformer-{{ version }}.tar.gz
  sha256: 038b7620e511789d6e8905aaeb687911ecea1c61f09980dddff8d7ad95cb77fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - boto3
    - botocore
    - einops >=0.3.0
    - h5py >=2.10.0
    - matplotlib-base
    - nvidia-apex
    - omegaconf
    - netcdf4
    - opencv
    - pandas
    - pytorch
    - regex
    - requests
    - scipy
    - tensorboard
    - pytorch-lightning==1.7.7
    - torchvision
    - tqdm
    - transformers >=4.3.0
    - xarray

test:
  imports:
    - earthformer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/earthformer
  summary: A Python package for Earth forecasting transformer (Earthformer)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
