{% set name = "earthformer" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/earthformer-{{ version }}.tar.gz
  sha256: 8f750a74d42ded9cae0f79105532b9dfd2c8f20d74e31ff6b5894793e9f7dd43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - boto3
    - botocore
    - earthnet
    - einops >=0.3.0
    - h5py >=2.10.0
    - matplotlib-base
    - nvidia-apex
    - omegaconf
    - netcdf4
    - opencv
    - pandas
    - pytorch
    - regex
    - requests
    - scipy
    - tensorboard
    - pytorch-lightning ==1.7.7
    - torchvision
    - tqdm
    - transformers >=4.3.0
    - xarray
    # additional dependencies
    # - contextvars
    # - fairscale
    - absl-py
    - awscli
    - einops
    # - fvcore
    - graphviz
    - jsonlines
    - networkx
    - pympler
    - protobuf
    - pyarrow
    - timm
    - unidiff
    - yacs
    - leafmap
    - localtileserver
    - geopandas

test:
  imports:
    - earthformer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/earthformer
  summary: A Python package for Earth forecasting transformer (Earthformer)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
